export const fallbackProducts = [
  {
    _id: 'fallback-1',
    name: 'Signature Draped Set',
    slug: 'signature-draped-set',
    description: 'A premium flowing set crafted for statement elegance and effortless movement.',
    category: 'Luxury Sets',
    price: 128,
    stock: 28,
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=900&q=80',
    rating: 4.9,
    featured: true,
  },
  {
    _id: 'fallback-2',
    name: 'Soft Linen Abaya',
    slug: 'soft-linen-abaya',
    description: 'Lightweight linen texture tailored for comfort with a refined silhouette.',
    category: 'Essentials',
    price: 84,
    stock: 40,
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
    rating: 4.8,
    featured: false,
  },
  {
    _id: 'fallback-3',
    name: 'Evening Silk Wrap',
    slug: 'evening-silk-wrap',
    description: 'An evening-first drape with rich texture and graceful finishing details.',
    category: 'Occasion Wear',
    price: 156,
    stock: 15,
    image: 'https://images.unsplash.com/photo-1487412912498-0447578fcca8?auto=format&fit=crop&w=900&q=80',
    rating: 5,
    featured: true,
  },
  {
    _id: 'fallback-4',
    name: 'Ayanfe Monogram Tote',
    slug: 'ayanfe-monogram-tote',
    description: 'Structured tote with signature monogram details and modern day-to-night style.',
    category: 'Accessories',
    price: 58,
    stock: 52,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
    rating: 4.7,
    featured: false,
  },
  {
    _id: 'fallback-5',
    name: 'Tailored Organza Shirt',
    slug: 'tailored-organza-shirt',
    description: 'Soft organza layers meet precise tailoring for a luxury minimalist wardrobe.',
    category: 'Essentials',
    price: 92,
    stock: 34,
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80',
    rating: 4.9,
    featured: true,
  },
  {
    _id: 'fallback-6',
    name: 'Festive Pleat Dress',
    slug: 'festive-pleat-dress',
    description: 'A celebratory look with sculpted pleats and confident, feminine structure.',
    category: 'Occasion Wear',
    price: 144,
    stock: 20,
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80',
    rating: 4.8,
    featured: true,
  },
];
